name: Make Binary

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: get python source
              run: wget https://www.python.org/ftp/python/3.11.9/Python-3.11.9.tgz -O python.tar.gz
            - name: extract python source
              run: tar -xvf python.tar.gz
            - name: install dependencies
              run: sudo apt-get install -y build-essential libncursesw5-dev libgdbm-dev libc6-dev zlib1g-dev libbz2-dev liblzma-dev libssl-dev libffi-dev
            - name: configure python
              run: |
                  cd Python-3.11.9
                  echo $(pwd)
                  ./configure --prefix=$(pwd)/Python-3.11.9/python-build --with-ensurepip=install --enable-optimizations
            - name: make python
              run: |
                  cd Python-3.11.9
                  make -j$(nproc)
                  make install
            - name: Zip python
              if: false
              run: |
                7z a python.zip ./Python-3.11.9/python-build/*/*
                ls -lh python.zip
            - name: Upload python
              uses: actions/upload-artifact@v3
              with:
                name: python
                path:  $(pwd)/Python-3.11.9/python-build/*
              