name: Make Binary

on:
    workflow_dispatch:
      inputs:
        python_version:
          type: string
          default: "3.11.9"
          description: Python version to build

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest,ubuntu-latest,macos-13]
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v3
            - name: get build date
              run: echo "build-date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
            - name: get python source
              run: wget https://www.python.org/ftp/python/${{inputs.python_version}}/Python-${{inputs.python_version}}.tgz -O python.tar.gz
            - name: extract python source
              run: tar -xvf python.tar.gz
            - name: install dependencies
              run: sudo apt-get install -y build-essential libncursesw5-dev libgdbm-dev libc6-dev zlib1g-dev libbz2-dev liblzma-dev libssl-dev libffi-dev
            - name: configure python
              run: |
                  cd Python-${{inputs.python_version}}
                  echo $(pwd)
                  ./configure --prefix=$(pwd)/Python-${{inputs.python_version}}/python-build --with-ensurepip=install
                  echo build-path=$(pwd)/Python-${{inputs.python_version}}/python-build >> $GITHUB_ENV
            - name: make python
              run: |
                  cd Python-${{inputs.python_version}}
                  make -j$(nproc)
                  make install
            - name: Zip python
              run: |
                7z a python.zip ${{env.build-path}}
                tar -czvf python.tar.gz ${{env.build-path}}
                ls -lh python.*
            - name: Upload python
              uses: actions/upload-artifact@v3
              with:
                name: python
                path:  python.*
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: build-${{env.build-date}}
                files: |
                   python.tar.gz
                   python.zip
